-- `esti.zenzobs.com`.TA_PRJ_PROJECT definition
DROP TABLE IF EXISTS `TA_PRJ_PROJECT`;
CREATE TABLE `TA_PRJ_PROJECT`  (
  `I_ID` int(11) NOT NULL AUTO_INCREMENT,
  `T_Code_01` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `T_Code_02` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `T_Name` varchar(750) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `I_Parent` int(11) NULL DEFAULT NULL COMMENT 'Project - Epic (1 or N level) - Task (1 or N level) ',
  `I_Group` int(11) NOT NULL COMMENT 'I_Group = I_ID of first parent => for index and rapid search,\nAny epic, task have the same i_group',
  `I_Type_00` int(11) NULL DEFAULT NULL,
  `I_Type_01` int(11) NULL DEFAULT NULL COMMENT 'Business, software...',
  `I_Type_02` int(11) NULL DEFAULT NULL,
  `I_Type_03` int(11) NULL DEFAULT NULL,
  `T_Info_01` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `T_Info_02` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL COMMENT 'lst of status:: 0: new, 1: todo, 2: in progress, 3: stand by, 4: done, 5: closed, 6: unresolved',
  `T_Info_03` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `I_Status_01` int(11) NULL DEFAULT NULL COMMENT '0: new, 1: todo, 2: in progress, 3: stand by, 4: done, 5: closed, 6: unresolved ',
  `I_Status_02` int(11) NULL DEFAULT NULL COMMENT 'other status',
  `I_Level` int(11) NULL DEFAULT NULL COMMENT 'level of priority',
  `D_Date_01` datetime NULL DEFAULT NULL COMMENT 'D_Date_New',
  `D_Date_02` datetime NULL DEFAULT NULL COMMENT 'D_Date_Mod',
  `D_Date_03` datetime NULL DEFAULT NULL COMMENT 'D_Date_Begin',
  `D_Date_04` datetime NULL DEFAULT NULL COMMENT 'D_Date_End',
  `I_Per_Manager` int(11) NULL DEFAULT NULL COMMENT 'Company/person owns project',
  `I_Aut_User_01` int(11) NULL DEFAULT NULL COMMENT 'User who create the project',
  `I_Aut_User_02` int(11) NULL DEFAULT NULL COMMENT 'Last user modify content',
  `F_Val_01` double NULL DEFAULT NULL COMMENT 'Val used for evaluation something: % of project,  val of project, propability',
  `F_Val_02` double NULL DEFAULT NULL,
  `F_Val_03` double NULL DEFAULT NULL,
  `F_Val_04` double NULL DEFAULT NULL,
  `F_Val_05` double NULL DEFAULT NULL,
  `F_Val_00` double NULL DEFAULT NULL,
  `F_Val_06` double NULL DEFAULT NULL,
  `F_Val_07` double NULL DEFAULT NULL,
  `F_Val_08` double NULL DEFAULT NULL,
  `F_Val_09` double NULL DEFAULT NULL,
  PRIMARY KEY (`I_ID`) USING BTREE,
  INDEX `idx_TPPRO_00`(`T_Code_01`) USING BTREE,
  INDEX `idx_TPPRO_01`(`T_Code_02`) USING BTREE,
  INDEX `idx_TPPRO_02`(`T_Name`) USING BTREE,
  INDEX `idx_TPPRO_06`(`I_Group`) USING BTREE,
  INDEX `idx_TPPRO_03`(`I_Type_01`) USING BTREE,
  INDEX `idx_TPPRO_05`(`I_Type_02`) USING BTREE,
  INDEX `idx_TPPRO_07`(`I_Type_00`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 1046 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;